vim.keymap.set('n', '<C-n>', ':cnext<CR>')
vim.keymap.set('n', '<C-p>', ':cprev<CR>')
vim.keymap.set('n', '<leader>qo', ':copen<CR>')
vim.keymap.set('n', '<leader>qq', ':cclose<CR>')
vim.keymap.set('n', '<esc>', ':cclose<CR>')
