wallpaper  {
    monitor = eDP-1
    path = ~/.local/share/wallpaper/main-mon.png
    fit_mode = cover
}
wallpaper  {
    monitor = HDMI-A-1
    path = ~/.local/share/wallpaper/external-mon.png
    fit_mode = cover
}

ipc = false
