local private = require("private")

hl.bind("SUPER + O", hl.dsp.exec_cmd("uwsm app -- bash -c 'grim -g \"$(slurp -d)\" -    | wl-copy ; notify-send -t 5000 \"Grim\" \"screenshot copied to clipboard\"'"), { release = true })
hl.bind("SUPER + A", hl.dsp.exec_cmd("uwsm app -- bash -c 'grim -c -                  | wl-copy ; notify-send -t 5000 \"Grim\" \"screenshot copied to clipboard\"'"), { release = true })
hl.bind("SUPER + CTRL + O", hl.dsp.exec_cmd("uwsm app -- bash -c 'grim -g \"$(slurp -d)\" -    | satty --filename -'"), { release = true })
hl.bind("SUPER + CTRL + A", hl.dsp.exec_cmd("uwsm app -- bash -c 'grim -c -                  | satty --filename -'"), { release = true })
hl.bind("SUPER + SHIFT + O", hl.dsp.exec_cmd("uwsm app -- bash -c 'grim -g \"$(slurp -d)\" ; notify-send -t 5000 \"Grim\" \"screenshot is saved\"'"), { release = true })
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("uwsm app -- bash -c 'grim -c; notify-send grim -t 5000 \"Grim\" \"Screenshot is saved.\"'"), { release = true })
hl.bind("SUPER + semicolon", hl.dsp.exec_cmd("uwsm app -- hyprpicker -an"))
hl.bind("SUPER + space", hl.dsp.exec_cmd("fuzzel"))

hl.bind("SUPER + V", hl.dsp.exec_cmd("~/.local/bin/history-picker.nu"))
hl.bind("SUPER + U", hl.dsp.exec_cmd("uwsm app -- ~/.local/bin/passmenu"))

hl.bind("SUPER + T", hl.dsp.exec_cmd("uwsm app -- alacritty"), { release = true })
hl.bind("SUPER + D", hl.dsp.exec_cmd("uwsm app -- zen"), { release = true })
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("uwsm app -- zen --private-window"), { release = true })
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("uwsm stop"), { release = true })
hl.bind("SUPER + E", hl.dsp.exec_cmd("emoji.sh"))
hl.bind("SUPER + Z", hl.dsp.exec_cmd("monitors on"), { locked = true })
hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd("monitors off"), { locked = true })
hl.bind("code:124", hl.dsp.exec_cmd("monitors toggle"), { locked = true })

hl.bind("SUPER + I", hl.dsp.exec_cmd("hypr_shortcuts"))
hl.bind("SUPER + SHIFT + I", hl.dsp.exec_cmd("hypr_shortcuts -E"), { release = true })
hl.bind("SUPER + X", hl.dsp.exec_cmd("uwsm app -- hyprlock"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("dunstctl close"))
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("dunstctl close-all"), { release = true })
hl.bind("SUPER + CTRL + N", hl.dsp.exec_cmd("dunstctl set-paused toggle"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SINK@ toggle"), { locked = true })
hl.bind("code:183", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SINK@ toggle"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SOURCE@ toggle"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("mpc -h " .. os.getenv("MPD_HOST") .. " toggle"), { locked = true })
hl.bind("SUPER + code:67", hl.dsp.exec_cmd("mpc -h " .. os.getenv("MPD_HOST") .. " toggle"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("mpc -h " .. os.getenv("MPD_HOST") .. " prev"), { locked = true })
hl.bind("SUPER + code:68", hl.dsp.exec_cmd("mpc -h " .. os.getenv("MPD_HOST") .. " prev"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("mpc -h " .. os.getenv("MPD_HOST") .. " next"), { locked = true })
hl.bind("SUPER + code:69", hl.dsp.exec_cmd("mpc -h " .. os.getenv("MPD_HOST") .. " next"), { locked = true })
hl.bind("code:208", hl.dsp.exec_cmd("mpc -h " .. os.getenv("MPD_HOST") .. " play"), { locked = true })
hl.bind("code:209", hl.dsp.exec_cmd("mpc -h " .. os.getenv("MPD_HOST") .. " pause"), { locked = true })

hl.bind("code:232", hl.dsp.exec_cmd("light -U 2"), { locked = true, repeating = true })
hl.bind("code:233", hl.dsp.exec_cmd("light -A 2"), { locked = true, repeating = true })

hl.bind("SUPER + W", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind("SUPER + SHIFT + W", hl.dsp.window.fullscreen())
hl.bind("SUPER + SHIFT + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + M", hl.dsp.window.pin())
hl.bind("SUPER + minus", hl.dsp.layout("togglesplit"))
hl.bind("SUPER + backspace", hl.dsp.window.pseudo())

-- hl.bind("SUPER + backslash", hl.dsp.focus({ direction = "c" }))
-- hl.bind("SUPER + SHIFT + backslash", hl.dsp.focus({ direction = "p" }))

hl.bind("SUPER + left", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "d" }))

hl.bind("SUPER + H", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = "d" }))

hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }))

hl.bind("SUPER + apostrophe", hl.dsp.focus({ workspace = "1" }))
hl.bind("SUPER + comma", hl.dsp.focus({ workspace = "2" }))
hl.bind("SUPER + period", hl.dsp.focus({ workspace = "3" }))
hl.bind("SUPER + P", hl.dsp.focus({ workspace = "4" }))
hl.bind("SUPER + Y", hl.dsp.focus({ workspace = "5" }))
hl.bind("SUPER + F", hl.dsp.focus({ workspace = "6" }))
hl.bind("SUPER + G", hl.dsp.focus({ workspace = "7" }))
hl.bind("SUPER + C", hl.dsp.focus({ workspace = "8" }))
hl.bind("SUPER + R", hl.dsp.focus({ workspace = "9" }))
hl.bind("SUPER + slash", hl.dsp.focus({ workspace = "10" }))

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "9" }))

hl.bind("SUPER + SHIFT + apostrophe", hl.dsp.window.move({ workspace = "1" }))
hl.bind("SUPER + SHIFT + comma", hl.dsp.window.move({ workspace = "2" }))
hl.bind("SUPER + SHIFT + period", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + SHIFT + P", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + SHIFT + Y", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + SHIFT + F", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + SHIFT + G", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + SHIFT + C", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + SHIFT + R", hl.dsp.window.move({ workspace = "9" }))

hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special" }))
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special())

hl.bind("SUPER + Tab", hl.dsp.focus({ last = true }))

hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("SUPER + grave", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    hl.bind("l", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("k", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("j", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })

    hl.bind("Escape", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
end)
