windowrulev = match:title:Firefox — Sharing Indicator,maxsize 60 35
windowrulev = match:title:Firefox — Sharing Indicator,float
windowrulev = match:title:Firefox — Sharing Indicator,nofocus
windowrulev = match:title:Firefox — Sharing Indicator,move 50% 95%
# windowrulev2 = nofullscreenrequest,title:Firefox — Sharing Indicator
windowrulev = match:class:org.gnome.Calculator,float
windowrulev = match:title:App,float
windowrulev = match:class:gnucash,title:GnuCash Tip Of The Day,float
windowrulev = match:class:gnucash,title:GnuCash Tip Of The Day,maxsize  60% 40%
windowrulev = match:class:org.gnome.Calculator,size 670 670
windowrulev = match:class:Element,monitor $main_monitor

windowrulev = match:title:log-plot,float

workspace = special:element,monitor:$main_monitor
workspace = special,monitor:$main_monitor
workspace = 1,monitor:$main_monitor
workspace = 2,monitor:$main_monitor, default:true
workspace = 3,monitor:$main_monitor
workspace = 4,monitor:$main_monitor
workspace = 5,monitor:$main_monitor
workspace = 6,monitor:$external_monitor
workspace = 7,monitor:$external_monitor
workspace = 8,monitor:$external_monitor, default:true
workspace = 9,monitor:$external_monitor
workspace = 10,monitor:$external_monitor

windowrulev = match: class:ueberzug,noanim
