theme = "ayu_mirage"

[editor]
line-number = "relative"
mouse = false
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎" 

[editor.whitespace.render]
newline = "all"

