require('plugins')
require('config')
require('telescope_conf')
require('easy_motion_conf')
require('treesitter_conf')
require('lua_line_conf')
require('cmp_conf')
require('nerdcommenter_conf')
require('colorscheme')
require('nvim-tree_conf')
require('fugitive_conf')
require('utils')
-- require('lsp')
require('null-ls_conf')
require('key_maps')
require('rust_tools_cfg')
