# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
[treesitter]
# auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_highlight = [
    "python",
    "toml",
    "norg",
    "norg-meta",
    "lua",
    "bash",
    "c",
    "cpp",
    "html",
    "json",
    "markdown",
    "rust",
    "sql",
    "yaml",
    "vim",
    "vimdoc"

]
auto_install = "prompt" # true | false

[treesitter.parser_map]
# You can add custom filetype to parser mappings.
# Determine the filetype with ':lua =vim.bo[0].filetype'.
# NOTE: You don't actually have to add these examples.
# They are added by default.
PKGBUILD = "bash"
cls = "latex"
sty = "latex"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
neorg = "8.7.1"
nvim-surround = "2.1.5"


[plugins.neorg-telescope]
git = "nvim-neorg/neorg-telescope"
rev = "v1.2.1"



[plugins.nvim-highlight-colors]
git = "brenoprata10/nvim-highlight-colors"

